version: '3'

services:

  mongo:
    image: mongo:4.0
    expose:
      - 27017

  oscar-controller:
    build: ./oscar-controller/
    ports:
      - 8081:8081
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    volumes:
      - /tmp/oscar:/tmp/oscar
    depends_on:
      - mongo

  oscar-downloader:
    build: ./oscar-downloader/
    ports:
      - 8082:8082
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    volumes:
      - /tmp/oscar:/tmp/ort

  oscar-ort:
    build: ./oscar-ort/
    volumes:
      - /tmp/oscar:/tmp/oscar

  oscar-fossology:
    build: ./oscar-fossology/
    volumes:
      - /tmp/oscar:/tmp/oscar
