version: '3'

services:

  mongo:
    image: mongo:4.0
    expose:
      - 27017

  oscar-controller:
    build: ./oscar-controller/
    ports:
      - 8081:8081
    volumes:
      - ./appdata:/tmp/ort
    depends_on:
      - mongo

  oscar-ort:
    build: ./oscar-ort/
    volumes:
      - ./appdata:/tmp/ort

  oscar-downloader:
    build: ./oscar-downloader/
    ports:
      - 8082:8082
    volumes:
      - ./appdata:/tmp/ort

  oscar-fossology:
    build: ./oscar-fossology/
    ports:
      - 3000:3000
    volumes:
      - ./appdata:/tmp/ort
